### ISSUE TITLE
cwcwidth/_impl.c:6:10: fatal error: 'Python.h' file not found

### ISSUE THREAD

**Issue by gsl-ghassengabsi** [sebastinas/cwcwidth#11]
hello, 
i tried to install cwcwidth with two ways in my macbook , and i had this issue:

`
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cwcwidth
  Building wheel for cwcwidth (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for cwcwidth (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-39
      creating build/lib.macosx-10.9-universal2-cpython-39/cwcwidth
      copying cwcwidth/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/cwcwidth
      copying cwcwidth/_impl.pyi -> build/lib.macosx-10.9-universal2-cpython-39/cwcwidth
      copying cwcwidth/py.typed -> build/lib.macosx-10.9-universal2-cpython-39/cwcwidth
      running build_ext
      skipping 'cwcwidth/_impl.c' Cython extension (up-to-date)
      building 'cwcwidth._impl' extension
      creating build/temp.macosx-10.9-universal2-cpython-39
      creating build/temp.macosx-10.9-universal2-cpython-39/cwcwidth
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -D_XOPEN_SOURCE=600 -I/Users/ghassen.gabsi/env-test/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -c cwcwidth/_impl.c -o build/temp.macosx-10.9-universal2-cpython-39/cwcwidth/_impl.o
      cwcwidth/_impl.c:6:10: fatal error: 'Python.h' file not found
      #include "Python.h"
               ^~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cwcwidth
Failed to build cwcwidth
ERROR: Could not build wheels for cwcwidth, which is required to install pyproject.toml-based projects`

Can you help me please?
Thank you

**Comment by sebastinas** [comment]
You seem to be missing Python's development headers.

**Comment by gsl-ghassengabsi** [comment]
hello, it's this , thank you, it works well now
